install.packages("ggplot2")
library(datasets)
df<-data(iris)
summary(iris)
library(ggplot2)
View(df)
names(iris) <- tolower(names(iris))
install.packages("dplyr")
library(dplyr)
virginica <- filter(iris, species == "virginica")
plot(iris)
plot(iris$sepal.width, iris$sepal.length)
hist(iris$sepal.width)
